---
apiVersion: v2
name: hive-operator
version: "25.11.0-rc1"
appVersion: "25.11.0-rc1"
description: The Stackable Operator for Apache Hive
home: https://github.com/stackabletech/hive-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
