---
version: 0.1.0
spec:
  units:
    - unit: &unitUri
        name: "uri"
        regex: "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?"
        examples:
          - "ldap://[2001:db8::7]/c=GB?objectClass?one"
        comment: "Specified in https://tools.ietf.org/html/rfc3986#appendix-B"
    - unit: &unitDirectory
        name: "directory"
        regex: "^/|(/[\\w-]+)+$"
        examples:
          - "/tmp/xyz"
    - unit: &unitClassName
        name: "classname"
        regex: "([a-zA-Z_$][a-zA-Z\\d_$]*\\.)*[a-zA-Z_$][a-zA-Z\\d_$]*"
        examples:
          - "org.apache.derby.jdbc.EmbeddedDriver"

properties:
  - property:
      propertyNames:
        - name: "networkaddress.cache.ttl"
          kind:
            type: "file"
            file: "security.properties"
      datatype:
        type: "integer"
        min: "0"
      recommendedValues:
        - fromVersion: "0.0.0"
          value: "30"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
      comment: "TTL for successfully resolved domain names."
      description: "TTL for successfully resolved domain names."

  - property:
      propertyNames:
        - name: "networkaddress.cache.negative.ttl"
          kind:
            type: "file"
            file: "security.properties"
      datatype:
        type: "integer"
        min: "0"
      recommendedValues:
        - fromVersion: "0.0.0"
          value: "0"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
      comment: "TTL for domain names that cannot be resolved."
      description: "TTL for domain names that cannot be resolved."

  - property:
      propertyNames:
        - name: "hive.metastore.port"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "integer"
        min: "1024"
        max: "65535"
      defaultValues:
        - value: "9083"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
  - property:
      propertyNames:
        - name: "hive.metastore.metrics.enabled"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "bool"
      defaultValues:
        - value: "false"
      roles:
        - name: "metastore"
          required: false
      asOfVersion: "0.0.0"
  - property:
      propertyNames:
        - name: "hive.metastore.warehouse.dir"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
        unit: *unitUri
      defaultValues:
        - value: "/user/hive/warehouse"
      roles:
        - name: "metastore"
          required: false
      description: "URI of the default location for native tables."
      asOfVersion: "0.0.0"
